apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imagemanager-data
  namespace: eda-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi # app-set: ${uploadStorageSize}
