apiVersion: v1
kind: Service
metadata:
  name: eda-imagemanager
  namespace: eda-system
spec:
  type: ClusterIP
  selector:
    eda.nokia.com/app: eda-imagemanager
  ports:
    - name: serving
      port: 8443
      targetPort: serving
