#!/usr/bin/env python3
# Generated by edabuilder from your Go API. Do not edit any files under pysrc, as they will be removed/overwritten.

import eda_common as eda

from . import constants
from . import ext_k8s_io_apimachinery_pkg_apis_meta_v1

IMAGEMANAGERCONFIG_SCHEMA = eda.Schema(group="imagemanager.eda.edacommunity.com", version="v1alpha1", kind="ImageManagerConfig")


class ImageManagerConfigSpec:
    def __init__(
        self,
        file_pull_base_url: str | None = None,
        default_artifact_namespace: str | None = "eda",
        default_repo: str | None = "images",
        max_upload_mi_b: int | None = 4096,
    ):
        self.default_artifact_namespace = default_artifact_namespace
        self.default_repo = default_repo
        self.max_upload_mi_b = max_upload_mi_b
        self.file_pull_base_url = file_pull_base_url

    def to_input(self):
        _rval = {}
        if self.default_artifact_namespace is not None:
            _rval[constants.Y_DEFAULTARTIFACTNAMESPACE] = self.default_artifact_namespace
        if self.default_repo is not None:
            _rval[constants.Y_DEFAULTREPO] = self.default_repo
        if self.max_upload_mi_b is not None:
            _rval[constants.Y_MAXUPLOADMIB] = self.max_upload_mi_b
        if self.file_pull_base_url is not None:
            _rval[constants.Y_FILEPULLBASEURL] = self.file_pull_base_url
        return _rval

    @staticmethod
    def from_input(obj) -> "ImageManagerConfigSpec | None":
        if not obj:
            return None
        _default_artifact_namespace = obj.get(constants.Y_DEFAULTARTIFACTNAMESPACE, "eda")
        _default_repo = obj.get(constants.Y_DEFAULTREPO, "images")
        _max_upload_mi_b = obj.get(constants.Y_MAXUPLOADMIB, 4096)
        _file_pull_base_url = obj.get(constants.Y_FILEPULLBASEURL)
        return ImageManagerConfigSpec(
            default_artifact_namespace=_default_artifact_namespace,
            default_repo=_default_repo,
            max_upload_mi_b=_max_upload_mi_b,
            file_pull_base_url=_file_pull_base_url,
        )


class TrackedArtifact:
    def __init__(
        self,
        name: str,
        namespace: str,
        repo: str,
        file_path: str,
        download_status: str | None = None,
        status_reason: str | None = None,
        external_url: str | None = None,
    ):
        self.name = name
        self.namespace = namespace
        self.repo = repo
        self.file_path = file_path
        self.download_status = download_status
        self.status_reason = status_reason
        self.external_url = external_url

    def to_input(self):
        _rval = {}
        _rval[constants.Y_NAME] = self.name
        _rval[constants.Y_NAMESPACE] = self.namespace
        _rval[constants.Y_REPO] = self.repo
        _rval[constants.Y_FILEPATH] = self.file_path
        if self.download_status is not None:
            _rval[constants.Y_DOWNLOADSTATUS] = self.download_status
        if self.status_reason is not None:
            _rval[constants.Y_STATUSREASON] = self.status_reason
        if self.external_url is not None:
            _rval[constants.Y_EXTERNALURL] = self.external_url
        return _rval

    @staticmethod
    def from_input(obj) -> "TrackedArtifact | None":
        if not obj:
            return None
        _name = obj.get(constants.Y_NAME)
        _namespace = obj.get(constants.Y_NAMESPACE)
        _repo = obj.get(constants.Y_REPO)
        _file_path = obj.get(constants.Y_FILEPATH)
        _download_status = obj.get(constants.Y_DOWNLOADSTATUS)
        _status_reason = obj.get(constants.Y_STATUSREASON)
        _external_url = obj.get(constants.Y_EXTERNALURL)
        return TrackedArtifact(
            name=_name,
            namespace=_namespace,
            repo=_repo,
            file_path=_file_path,
            download_status=_download_status,
            status_reason=_status_reason,
            external_url=_external_url,
        )


class ImageManagerConfigStatus:
    def __init__(
        self,
        health: str | None = None,
        message: str | None = None,
        last_reconcile_time: str | None = None,
        uploads_stored: int | None = None,
        bytes_stored: int | None = None,
        artifacts: list[TrackedArtifact] | None = None,
        version: str | None = None,
    ):
        self.health = health
        self.message = message
        self.last_reconcile_time = last_reconcile_time
        self.uploads_stored = uploads_stored
        self.bytes_stored = bytes_stored
        self.artifacts = artifacts
        self.version = version

    def to_input(self):
        _rval = {}
        if self.health is not None:
            _rval[constants.Y_HEALTH] = self.health
        if self.message is not None:
            _rval[constants.Y_MESSAGE] = self.message
        if self.last_reconcile_time is not None:
            _rval[constants.Y_LASTRECONCILETIME] = self.last_reconcile_time
        if self.uploads_stored is not None:
            _rval[constants.Y_UPLOADSSTORED] = self.uploads_stored
        if self.bytes_stored is not None:
            _rval[constants.Y_BYTESSTORED] = self.bytes_stored
        if self.artifacts is not None:
            _rval[constants.Y_ARTIFACTS] = [x.to_input() for x in self.artifacts]
        if self.version is not None:
            _rval[constants.Y_VERSION] = self.version
        return _rval

    @staticmethod
    def from_input(obj) -> "ImageManagerConfigStatus | None":
        if not obj:
            return None
        _health = obj.get(constants.Y_HEALTH)
        _message = obj.get(constants.Y_MESSAGE)
        _last_reconcile_time = obj.get(constants.Y_LASTRECONCILETIME)
        _uploads_stored = obj.get(constants.Y_UPLOADSSTORED)
        _bytes_stored = obj.get(constants.Y_BYTESSTORED)
        _artifacts = []
        if obj.get(constants.Y_ARTIFACTS) is not None:
            for _e in obj.get(constants.Y_ARTIFACTS):
                _artifacts.append(TrackedArtifact.from_input(_e))
        _version = obj.get(constants.Y_VERSION)
        return ImageManagerConfigStatus(
            health=_health,
            message=_message,
            last_reconcile_time=_last_reconcile_time,
            uploads_stored=_uploads_stored,
            bytes_stored=_bytes_stored,
            artifacts=_artifacts,
            version=_version,
        )


class ImageManagerConfig:
    def __init__(
        self,
        kind: str | None = None,
        api_version: str | None = None,
        metadata: ext_k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta | None = None,
        spec: ImageManagerConfigSpec | None = None,
        status: ImageManagerConfigStatus | None = None,
    ):
        self.kind = kind
        self.api_version = api_version
        self.metadata = metadata
        self.spec = spec
        self.status = status

    def to_input(self):
        _rval = {}
        if self.kind is not None:
            _rval[constants.Y_KIND] = self.kind
        if self.api_version is not None:
            _rval[constants.Y_APIVERSION] = self.api_version
        if self.metadata is not None:
            _rval[constants.Y_METADATA] = self.metadata.to_input()
        if self.spec is not None:
            _rval[constants.Y_SPEC] = self.spec.to_input()
        if self.status is not None:
            _rval[constants.Y_STATUS] = self.status.to_input()
        return _rval

    @staticmethod
    def from_input(obj) -> "ImageManagerConfig | None":
        if not obj:
            return None
        _kind = obj.get(constants.Y_KIND)
        _api_version = obj.get(constants.Y_APIVERSION)
        _metadata = (
            ext_k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta.from_input(obj.get(constants.Y_METADATA))
            if obj.get(constants.Y_METADATA, None)
            else ext_k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta.from_name(obj.get(constants.Y_NAME))
        )
        _spec = ImageManagerConfigSpec.from_input(obj.get(constants.Y_SPEC))
        _status = ImageManagerConfigStatus.from_input(obj.get(constants.Y_STATUS))
        return ImageManagerConfig(
            kind=_kind,
            api_version=_api_version,
            metadata=_metadata,
            spec=_spec,
            status=_status,
        )


class ImageManagerConfigList:
    def __init__(
        self,
        items: list[ImageManagerConfig],
        kind: str | None = None,
        api_version: str | None = None,
        metadata: ext_k8s_io_apimachinery_pkg_apis_meta_v1.ListMeta | None = None,
    ):
        self.kind = kind
        self.api_version = api_version
        self.metadata = metadata
        self.items = items

    def to_input(self):
        _rval = {}
        if self.kind is not None:
            _rval[constants.Y_KIND] = self.kind
        if self.api_version is not None:
            _rval[constants.Y_APIVERSION] = self.api_version
        if self.metadata is not None:
            _rval[constants.Y_METADATA] = self.metadata.to_input()
        _rval[constants.Y_ITEMS] = [x.to_input() for x in self.items]
        return _rval

    @staticmethod
    def from_input(obj) -> "ImageManagerConfigList | None":
        if not obj:
            return None
        _kind = obj.get(constants.Y_KIND)
        _api_version = obj.get(constants.Y_APIVERSION)
        _metadata = ext_k8s_io_apimachinery_pkg_apis_meta_v1.ListMeta.from_input(obj.get(constants.Y_METADATA))
        _items = []
        if obj.get(constants.Y_ITEMS) is not None:
            for _e in obj.get(constants.Y_ITEMS):
                _items.append(ImageManagerConfig.from_input(_e))
        return ImageManagerConfigList(
            kind=_kind,
            api_version=_api_version,
            metadata=_metadata,
            items=_items,
        )
